name: Publish

on:
  push:
    branches: [ development ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js dependencies
      run: npm install

    - name: Build project
      run: ./build.sh

    - name: Copy static files
      run: cp src/social.jpg src/404.html src/favicon.ico src/CNAME public

    - name: Initialize worktree
      run: |
        git worktree add -b master ../wavetilt-www-master
        cd ../wavetilt-www-master
        git fetch origin master
        git reset --hard origin/master

    - name: Copy files
      run: |
        link ../wavetilt-www-master/.git ../wt-www.git
        rsync -vrptx --delete public/ ../wavetilt-www-master/
        link ../wt-www.git ../wavetilt-www-master/.git

    - name: Commit
      run: |
        cd ../wavetilt-www-master
        git add -A
        git -c user.name=Wavetilt -c user.email=github@wavetilt.com commit -C $(git log -1 --oneline --pretty=%H development)
        git log

    - name: Publish
      run: |
        cd ../wavetilt-www-master
        git push origin master
